AlreadyBored/nodejs-assignments

assignments/template-rest/assimnent.md
assignments/template-rest/score.md

Add existing endpoints, scoring

feat: add rest service module

---

README.md
assignments/authentication/assignment.md
assignments/authentication/score.md
assignments/crud-api/assignment.md

Authentication JWTAssignment  & Score
and corrected CRUD API Assignment

Bnjc 32 template improvements Authentication JWTAssignment & Score

---

assignments/authentication/assignment.md
assignments/crud-api/assignment.md

made some correction of mistales that skipped earlier.

Bnjc 32 template improvements authentication jwt assignment

---

assignments/crud-api/score.md

urls are  `/api/users` in task assignment
https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/assignment.md

fix api urls

---

assignments/authentication/assignment.md
assignments/crud-api/assignment.md
assignments/file-manager/assignment.md
assignments/logging-error-handling/assignment.md
assignments/remote-control/assignment.md
assignments/rest-service/assignment.md

Use the latest LTS node for all assignments

Unify node version requirements

---

assignments/remote-control/assignment.md
assignments/remote-control/score.md

I checked all calls with this library and we can change task to it. It doesn't need to build additional binary.

[websocket] change robotjs to nutjs library

---

assignments/graphql-service/assignment.md

It is also better to define for students interface Member like here for example:
https://github.com/rolling-scopes-school/node-graphql-service/blob/main/bands/src/classes/member.ts

fix: interface field type for consistency

---

assignments/crud-api/assignment.md

Fix a small typo in Crud API node.js assignment

Fix typo in Crud API node.js assignment

---

assignments/remote-control/assignment.md

Make it clear, that a Student have to clone the repo and write the code in the cloned repo.
(this PR was born because of [complaints from other students](https://discordapp.com/channels/755676888680366081/1057556451540877384/1065999618757890108), who didn't understand what to do. So let's minimize confusing)
cc @kele6ra

refactor: make it more clear where to start and what repository to use

---

assignments/rest-service/assignment.md

Updated 2022Q2 to 2022Q4 in assignment.md

Update rest-service assignment.md

---

assignments/rest-service/score.md

This PR removes doubled `instance` words (typos)

Remove doubled `instance` words (typos)

---

assignments/rest-service/assignment.md

This PR fixes a typo:
```diff
- FavoritesRepsonse
+ FavoritesResponse
```

Fix typo in `FavoritesResponse`

---

assignments/logging-error-authentication-authorization/assignment.md

Remove duplicate requirement

---

assignments/crud-api/assignment.md

add missing option based on last commit 0f44f5331657a333be37a6732d1986c9967fb1c4 https://github.com/AlreadyBored/nodejs-assignments/commit/a6e98e3f917d7b2fc5baa9169aa8c23ac2dfbd59

docs: add missing option

---

assignments/battleship/assignment.md

update attack and turn description

[nodejs] websocket improve description

---

assignments/battleship/assignment.md

websocket  task clarification

---

assignments/rest-service/assignment.md

Write actyally name repository

Update assignment.md - correct name repository

---

assignments/crud-api/assignment.md

1. added ts-loader in libraries list, because a lot of student ask "can we use ts-loader?", and I also try to find answer, and figure out that this question appear every time (it scare to add this library, because it doesn't have in list and have a risk to get -95% to score)
2. fix typo from "user" to "users", because we dont have api "/user/{userId}"

docs: add library to description and fix typo in api

---

assignments/nodejs-basics/assignment.md

Just two minor typos corrected ("doesn't exists" => "doesn't exist")

refactor: correct minor typos

---

assignments/nodejs-basics/assignment.md

before: - `list.js` - implement function that prints all array of filenames from `files` folder into console
after: - `list.js` - implement function that prints array of all filenames from `files` folder into console

Fix nodejs-basics assignment typo

---

assignments/crud-api/assignment.md
assignments/crud-api/score.md

During code review discussions, there was an ambiguity in the task requirements regarding the .env file handling. Some students interpreted the requirement to store port value in .env file as a necessity to commit this file for reviewers' convenience, while others were deducting points for having .env in repository, referring to security best practices.

docs: add note about env file

---

assignments/logging-error-authentication-authorization/assignment.md
assignments/logging-error-authentication-authorization/score.md

Reverts AlreadyBored/nodejs-assignments#104

Revert "Fix authentication assignment typo"
